- name: Execute alert_mgr_status.sh and alert_slave_status.sh
  shell: "{{ item }}"
  with_items:
    - "sh -x {{ shelldir }}/alert_proxysql_status.sh {{ admin_password }}"
  delegate_to: "{{item}}"
  with_items: "{{ groups['proxysql'] }}"