- name: Specify target database
  lineinfile:
    path: "{{ restore_target_data }}"
    regexp: "'^USE `{{ dbname }}`;'"
    line: "USE `{{ restore_target_database }}`;"
  with_items:
    - "{{ restore_target_data }}"
  when: restore_diff_database

- name: Import data
  mysql_db:
    login_user: root
    login_password: "{{ root_password }}"
    login_port: "{{ mysql_port }}"
    login_unix_socket: "{{ socket }}"
    state: import
    name: "{{ restore_target_database }}"
    target: "{{ restore_target_data }}"