---
# tasks file for scheduler_job

- include: password.yml
  when: >
        (initial_monitor_manage | default(False)) or
        (initial_xtrabackup | default(False))

- include: mysql_monitor_manage.yml
  when: initial_monitor_manage | default(False)

- include: mysql_xtrabackup.yml
  when: initial_xtrabackup | default(False)

- include: mysql_slow.yml
  when: initial_slow | default(False)

- include: execute_mysql_summary_job.yml
  when: execute_mysql_summary_job | default(False)

- include: execute_mysql_monitor_job.yml
  when: execute_mysql_monitor_job | default(False)

- include: execute_mysql_xtrabackup_job.yml
  when: execute_mysql_xtrabackup_job | default(False)

- include: execute_mysql_xtra_restore_job.yml
  when: execute_mysql_xtra_restore_job | default(False)

- include: execute_mysql_slow_job.yml
  when: execute_mysql_slow_job | default(False)

- include: execute_proxysql_monitor_job.yml
  when: execute_proxysql_monitor_job | default(False)

- include: execute_mysql_defragment_job.yml
  when: execute_mysql_defragment_job | default(False)

- include: execute_mysql_archive_job.yml
  when: execute_mysql_archive_job | default(False)

- include: execute_mysql_lock_monitor_job.yml
  when: execute_mysql_lock_monitor_job | default(False)