# Define automatic backup with xtrabackup
- name: Create a directory for backup
  file: path={{ item }} state=directory owner=mysql group=mysql
  with_items:
    - "{{ backupdir }}/chkpoint"
    - "{{ backupdir }}/log/xtrabackup_log"
    - "{{ backupdir }}/monitor"
    - "{{ backupdir }}/shell"
    - "{{ backupdir }}/databak/{{ ansible_hostname }}"
    - "{{ backupdir }}/archive"

- name: Rendering xtrabackup script file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: mysql
    group: mysql
    mode: 0744
  with_items:
    - { src: 'backup.sh.j2', dest: "{{ backupdir }}/shell/backup.sh" }
    - { src: 'mysql_xtrabackup.sh.j2', dest: "{{ backupdir }}/shell/mysql_xtrabackup.sh" }
    - { src: 'xtra_data_archiving.sh.j2', dest: "{{ backupdir }}/shell/xtra_data_archiving.sh" }

- name: Add log polling task schedule for xtrabackup
  cron:
    name: "auto xtrabackup"
    minute: "0"
    hour: "*/1"
    job: "{{ backupdir }}/shell/backup.sh > /dev/null 2>&1 &"

- name: Initialize the first full backup
  shell: "sh {{ backupdir }}/shell/mysql_xtrabackup.sh full"