- name: Create a directory for monitor
  file:
    state: directory
    owner: mysql
    group: mysql
    path: "{{ item }}"
  with_items:
    - "{{ monitordir }}"
    - "{{ shelldir }}"

- name: Add mysql_slowdigest job
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: mysql
    group: mysql
    mode: 0744
  with_items:
    - { src: 'mysql_slow_digest.sh.j2', dest: "{{ shelldir }}/mysql_slow_digest.sh" }
