- name: Create a directory for monitor
  file: >
        path={{ monitordir }} state=directory owner=mysql group=mysql
        path={{ shelldir }} state=directory owner=mysql group=mysql

- name: Add mysql_summary job
  template:
    src: pt_mysql_summary.sh.j2
    dest: "{{ shelldir }}/pt_mysql_summary.sh"
    owner: mysql
    group: mysql
    mode: 0744
  when: ansible_hostname in groups.mgr

- name: Add mysql_summary_collect_send job
  template:
    src: mysql_summary_collect_send.sh.j2
    dest: "{{ shelldir }}/mysql_summary_collect_send.sh"
    owner: mysql
    group: mysql
    mode: 0744
  when: ansible_hostname not in groups.mgr

- name: Add main_summary_body for mail
  copy:
    src: main_summary_body.txt
    dest: "{{ monitordir }}/main_summary_body.txt"
    owner: mysql
    group: mysql
    mode: 0644
  when: ansible_hostname not in groups.mgr