- name: Create a directory for monitor
  file: path={{ shelldir }} state=directory owner=mysql group=mysql

- name: Rendering monitor script file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: mysql
    group: mysql
    mode: 0744
  with_items:
    - { src: 'alert_mgr_status.sh.j2', dest: '{{ shelldir }}/alert_mgr_status.sh' }
    - { src: 'alert_slave_status.sh.j2', dest: '{{ shelldir }}/alert_slave_status.sh' }