- name: Create a directory for monitor
  file: path={{ shelldir }} state=directory owner=proxysql group=proxysql
  delegate_to: "{{item}}"
  with_items: "{{ groups['proxysql'] }}"

- name: Rendering monitor script file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: proxysql
    group: proxysql
    mode: 0744
  with_items:
    - { src: 'alert_proxysql_status.sh.j2', dest: '{{ shelldir }}/alert_proxysql_status.sh' }
  delegate_to: "{{item}}"
  with_items: "{{ groups['proxysql'] }}"